### ISSUE TITLE
[Auth] Spring Security 설정

### ISSUE THREAD

**Issue by IToriginal** [Team-SE-MO/semo-springboot-server#1]
## 📄 설명
Spring Security 기본 설정

## 🗓️ TO-DO
- [x] Spring Security 설정
- [x] Member, Company 패키지 구성
- [x] login/logout 구현

## ➕ ETC
Member, Company는 Spring Security 설정에서 필요 기능을 구현.
(단, API 개발과는 별개로 설정에 중심을 두기 때문에 Member, Company API 개발시 재개발 또는 검토 필요)
