### ISSUE TITLE
[Monitoring] v$session Data 수집 로직 개발

### ISSUE THREAD

**Issue by IToriginal** [Team-SE-MO/semo-springboot-server#16]
## 📄 설명
- 기술적인 검토 단계를 포함합니다. (`Spring Batch`)
- Database 연결이 올바른지 Test하고 Device Table Status 속성을 최신화 합니다.
- Device Table에 등록된 외부 장비의 정보로 DataBase 연결을 하고, 해당 DataBase의 session 정보를 수집합니다.
- `semo-batch` 모듈에서 작업 진행합니다. (Entity class는 `semo-core` 모듈에 생성)

## 🗓️ TO-DO
- [x] 데이터 수집 Entity 생성(semo-core 모듈에 위치)
- [x] 외부 DataBase 상태 확인 및 업데이트
- [x] 외부 DataBase 세션 정보 조회
- [x] 외부 DataBase 세션 정보를 SEMO DB에 INSERT
- [x] 데이터 수집 확인

## ➕ ETC
- 개발 초기 단계에서 수집 주기는 최소`1min` 최대 `5sec`이며, **성능을 고려하지 않습니다.**
- 생성한 이슈는 RDB(ORACLE)에 다이렉트로 JDBC를 이용해 `INSERT`하는 단계입니다.(REDIS, CSV FILE을 고려하지 않음)
