### ISSUE TITLE
[Refactor] MemberForm 도메인 Company 컬럼 추가 및 관련 로직 리팩토링 

### ISSUE THREAD

**Issue by dabeen-jung** [Team-SE-MO/semo-springboot-server#25]
## 📄 설명
- MemberForm 엔티티에 Company 연관관계를 수정 및 관련 company 부분의 코드를 전반적으로 리팩토링 할 예정입니다.

## 🗓️ TO-DO
- [x] MemberForm Company 연관관계 추가
- [x] 테이블 업데이트
- [x] 관련 비즈니스 로직 리팩토링
- [x] 고객사 회원가입 요청 - 목록조회 응답값 리팩토링

## ➕ ETC
- 이어서 남은 Member 개발을 진행 합니다.( 비밀번호 수정, 삭제(soft delete), 유저목록 조회(필터링)
