### ISSUE TITLE
[Monitoring] 세션 데이터 조회 API 구현 - 요약 정보

### ISSUE THREAD

**Issue by IToriginal** [Team-SE-MO/semo-springboot-server#35]
## 📄 설명
- DataBase Device 요약 정보 페이지에 사용될 조회 API를 구현합니다.

### 🖥️ 요약 정보 페이지
<img width="741" alt="image" src="https://github.com/user-attachments/assets/85c44c1c-bfb3-49aa-b2c6-a412cd3050f0">

## 🗓️ TO-DO
- [x] 패키지 병합 리팩토링: `Collection`, `Metric` 패키지 -> `Monitoring` 패키지
- [x] DTO 생성
- [x] 조회 Query 생성
- [x] Service Layer 비즈니스 로직 구현
- [x] RestAPI Controller Layer구현
