### ISSUE TITLE
[Monitoring] 세션 데이터 모니터링 조회 API 구현

### ISSUE THREAD

**Issue by smuhsh** [Team-SE-MO/semo-springboot-server#44]
## 📄 설명
- Session Data List 모니터링 페이지에 사용될 조회 API를 구현합니다.
- Session 데이터는 스케쥴러를 통해 5초마다 적재됩니다.
- 모니터링 조회시 현재 보고있는 화면은 고정된 상태에서 위로 row 가 적재되어 스크롤바 길이가 줄어듭니다. 

## 🖥️ 세션 데이터 모니터링 페이지
![image](https://github.com/user-attachments/assets/cc01cad2-105d-4f48-9be6-33a648dc6db4)

## 🗓️ TO-DO
- [x] 페이지 네이션 구현
- [x] 페이지 네이션 처리시 누락 데이터 검증
- [x] 관련 서비스 로직 구현
- [x] 페이징 조회위한 RestController 구현
- [x] 레포지토리 구현
