### ISSUE TITLE
[Member, Auth] 초기 비밀번호 변경 여부 관리하는 flag 구현, Jwt payload 및 필터 기능 리팩토링

### ISSUE THREAD

**Issue by juneheel** [Team-SE-MO/semo-springboot-server#47]
## 📄 설명
- Member 테이블 내에 flag column을 추가해 초기 비밀번호 변경여부를 확인하는 기능을 구현합니다. 

## 🗓️ TO-DO
- [x] Member 엔티티 수정
- [x] 비밀번호 설정 시 flag 변경 로직 구현
- [x] Jwt payload에 username 추가
- [ ] Jwt 토큰 필요여부에 따른 요청 필터링 구현 

## ➕ ETC
- 관련 이슈 : #26 #32
