### ISSUE TITLE
[Company, Form] 패키지 수정 및 회사 등록 API

### ISSUE THREAD

**Issue by dabeen-jung** [Team-SE-MO/semo-springboot-server#5]
## 📄 설명
Company Entity 수정 및 Form 테이블 생성에 관련하여 패키지를 생성합니다.
추가적으로 회사 등록 요청처리 API를 개발합니다.

## 🗓️ TO-DO
- [x] DB에 `COMPANY_REGISTER_FORM` , 'REGISTER_FORM` 생성
- [x] Company 엔티티 항목 추가
- [x] Form 패키지 생성 등록
- [ ] 회사 등록 요청 처리 API
