### ISSUE TITLE
[Meta Monitoring] 쿼리 작성 및 메타 통계 정보 조회 api 개발

### ISSUE THREAD

**Issue by dabeen-jung** [Team-SE-MO/semo-springboot-server#51]
## 📄 설명
- 쿼리 작성 및 피그마에 차트를 이용하여 디자인 합니다 

## 🗓️ TO-DO
- [x] 쿼리 구상
- [x] 피그마 작성
- [x] 메타 통계 - 실시간 세션 job 실행시간 조회 API
- [x] 메타 통계 - 일자별 Job(삭제,수집) 실행시간 조회 API
- [x]  메타 통계 - 일자별 Error Type 조회 API
- [ ]  메타 통계 - Error 정보 조회 API

## ➕ ETC
-
