### ISSUE TITLE
[Device] 생성, 조회 API 구현

### ISSUE THREAD

**Issue by IToriginal** [Team-SE-MO/semo-springboot-server#6]
## 📄 설명
Device(외부 Database) 관련 기본적인 API 개발

## 🗓️ TO-DO
- [x] Device Entity 클래스 생성
- [x] Device Connection 상태 확인 API 구현 (H/C)
- [x] Device 생성 API 구현
- [x] Device 조회 API 구현
- [x] Device password 암호화

## ➕ ETC
- 수정(U), 삭제(D)에 대해서는 다른 이슈를 생성해서 개발을 이어 진행할 예정
