### ISSUE TITLE
[Architecture] 멀티모듈 아키텍처 구성하기

### ISSUE THREAD

**Issue by IToriginal** [Team-SE-MO/semo-springboot-server#7]
## 📄 설명
데이터 수집 서버, API 서버, 도메인 Core로 나눠서 멀티모듈 아키텍처로 리팩토링

## 🗓️ TO-DO
- [x] semo-batch 모듈 생성: 외부 DB 데이터 수집을 담당하는 서버 - PORT. 8081
- [x] semo-api 모듈 생성: 서비스 애플리케이션을 담당하는 서버(Controller, Service) - PORT. 8080
- [x] semo-core 모듈 생성: 공통적으로 사용할 도메인을 구성(Entity, Repository, DTO ... )
<img width="500" alt="image" src="https://github.com/user-attachments/assets/b8b41a26-8de7-4d5a-8894-3d207e8aae54">
