### ISSUE TITLE
[Global] 서비스 로직 최적화

### ISSUE THREAD

**Issue by IToriginal** [Team-SE-MO/semo-springboot-server#71]
## 📄 설명
- 프로젝트 개발(2024-11-29)까지 발견되는 서버의 모든 문제를 발견하고 이를 해결합니다.

## 🗓️ TO-DO
- [x] [Monitoring] Session Data 초기 실행 시간 최적화</br>(🔗 #72)
- [x] [Monitoring] Batch Monitoring System 최신 데이터 정보가 웹 소켓 연결 시점에 따라 데이터가 존재함에도 0을 응답하는 문제</br>(🔗 #74)
- [x] 장비 요약 페이지에서 장비 정보의 정렬 기준을 수정 시간으로 수정</br>(🔗 #74)
